### PR TITLE
multiple additem

### PR DESCRIPTION
**Pull request by thimo1**
This adds the possibility to check/select all filtered items at once.

`
const filteredElements = props.options.filter(item => regexp.test(item[props.searchBy] || item[props.labelField]));
`

`
<Button
              onClick={
                () => methods.selectMultiple(filteredElements)
                // methods.selectAll
              }
            >
              Select all filtered
            </Button>
`

### CODE REVIEW

**Comment by sanusart** [comment]
How is this different from `selectAll` method?
Used here https://sanusart.github.io/react-dropdown-select/examples/#Custom-Content-And-Dropdown-renderers

**Comment by thimo1** [comment]
The selectAll method selects all, even unfiltered items. This function allows both, you can provide an array of elements you want to have selected like the filtered result and select all of them with a single click.

**Comment by sanusart** [comment]
Got it, so maybe it is better to allow parameter in `selectAll` method?
What do you think?

**Comment by thimo1** [comment]
I‘m not sure if it works that way but open minded :)

**Comment by sanusart** [comment]
Something like the following:

```javascript
selectAll = (valuesList) => {
  this.props.onSelectAll();
  const values = valuesList 
      ? valuesList 
      : this.props.options.filter((option) => !option.disabled);

  return this.setState({ values });
};
```

**Comment by thimo1** [comment]
👍
Will you push that?

**Comment by sanusart** [comment]
Sure thing, later tonight (I hope) will test and push.
Please don't close this PR for now.

**Comment by sanusart** [comment]
Thanks @thimo1 
Published v3.8.0

Example in demo:
https://sanusart.github.io/react-dropdown-select/examples/#Custom-Content-And-Dropdown-renderers

**Comment by thimo1** [comment]
Awesome, thanks!

**Pull request closed without merging**
